language: java
env:
  global:
    - BAZEL_INSTALL="${HOME}/bazel/install"
  matrix:
    - BAZEL_VERSION=0.5.4
    - BAZEL_VERSION=0.7.0
install:
  - mkdir -p $BAZEL_INSTALL
  - pushd $BAZEL_INSTALL
  - wget --no-clobber "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
  - sudo dpkg -i "bazel_${BAZEL_VERSION}-linux-x86_64.deb"
  - popd
script:
  - bazel build --verbose_failures //...:all

notifications:
  email: false
  slack: false

branches:
  only:
    - master
